spring:
  datasource:
    url: jdbc:mysql://112.124.12.211:3306/lyf_topic?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  rabbitmq:
    host: 112.124.12.211
    port: 5672
    virtual-host: /
    username: guest
    password: guest
  cloud:
    nacos:
      discovery:
        server-addr: 112.124.12.211:8848
  application:
    name: lyf-topic
mybatis-plus:

  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml

server:
  port: 9999


