spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.230.133:8848
  application:
    name: lyf--auth-service

  redis:
    host: 192.168.230.133
    port: 6379

server:
  port: 20000
